### ISSUE TITLE
The window with captured requests can not be closed

### ISSUE THREAD

**Issue by AlexByte** [google/tamperchrome#19] opened 2017-05-18 08:58 UTC
When I close it, it instantly opens again.
Also, after the "Replay Requests" function is enabled, the developer tools stops responding.

**Comment by sirdarckcat** [comment] 2017-05-18 10:49
Hi

Thanks for reporting it. I have seen these behaviors before but hadn't gotten the chance to document them.

1.  It reopens when there is a pending request. Try disabling the interceptors and that should make the window stop pooping up.

1.  About Replay Request, that's a UX problem. If you go through the list of requests you will notice that one of them is pending, and you need to click on "allow" so it gets unblocked.

Hopefully both problems will go away with the new UI in #18.

**Comment by sirdarckcat** [comment] 2017-05-18 10:58
What should be happening is that when you close the window, it reopens, when it reopens, the list of requests is still there. One of those requests (probably not the last one) is the "Replay" request that is blocking the extension, and you need to let it go (accept/block) so your browser can get unblocked.

The reason the UI is blocked is because is waiting for the answer to what to do with that request. This will hopefully be fixed in the next version of the UI.

**Comment by sirdarckcat** [comment] 2017-05-21 21:15
please let me know if this didnt work

**Comment by AlexByte** [comment] 2017-05-21 21:31
How can i accept/block request?

**Comment by sirdarckcat** [comment] 2017-05-21 21:36
I'll make a screencast to show you :-)

**Comment by sirdarckcat** [comment] 2017-05-22 22:36
well, nevermind.. when I was trying to make the screencast to show you, I was able to reproduce the bug.

you are right if you select all capture/replay options you can easily get in a situation when you get overwhelmed with requests, you close the window, and you can get back.

**Comment by AlexByte** [comment] 2017-05-22 22:38
One request in the window mean overwhelmed with requests?

**Comment by sirdarckcat** [comment] 2017-05-22 22:49
so you reported two things :)

1. When you close the window, it instantly opens again.
2. After the "Replay Requests" function is enabled, the developer tools stops responding.

The first is working as intended, because you can always just ignore the request, or disable the capturing and let it go, but if you have Replay Requests enabled, you can't disable "Capturing" if there is a pending request in the app, at the same time, if there is a pending request in the app, it gets focused, so you can't easily find the pending "Replay Request".

I will fix this for you somehow, maybe by showing a warning before the app's window is closed asking the user if all capturing options should be disabled.

Here's the video: https://youtu.be/kPZ4tRihekE - as you can see, this is a bug that needs to be fixed.

**Comment by AlexByte** [comment] 2017-05-22 22:52
I've checked only "Replay Request", so i have no "Allow" and "Block" buttons.

**Comment by sirdarckcat** [comment] 2017-05-22 22:58
I see, thanks.

It's the same problem, though. Probably two requests are sent to the app at the same time :)

**Comment by AlexByte** [comment] 2017-05-22 23:01
So my issue not about pending requests.

**Comment by sirdarckcat** [comment] 2017-05-22 23:06
I think it is.

Can you try to enable "Replay Requests", and going to ebay.com? I imagine you would have the same problem.

**Comment by AlexByte** [comment] 2017-05-22 23:27
One one request from tab is displayed in window. The issue is confirmed on site http://example.com

**Comment by AlexByte** [comment] 2017-05-22 23:55
I realized what the problem was. I had all the time to press the Send button. I thought I should be like in the panel Network.

**Comment by sirdarckcat** [comment] 2017-05-27 19:05
ah.. :)

**Closed by sirdarckcat** 2017-05-27 19:05 UTC
